/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2024-07-19

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32l4xx_hal.h"
#include "stm32l4xx.h"

#include <stdio.h>
/* FreeRTOS.org includes. */
#include "FreeRTOS.h"
#include "task.h"

TaskHandle_t myTask1Handle = NULL;
TaskHandle_t myTask2Handle = NULL;

#include "message_buffer.h"

// Define buffer size
#define BUFFER_SIZE 100

// Define a handle for the message buffer
MessageBufferHandle_t xMessageBuffer;

// Task function prototypes
void vTaskSender(void *pvParameters);
void vTaskReceiver(void *pvParameters);
/* MX_GPIO_Init() should be generated by CubeMX or manually defined */
void button_init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct;

    /* GPIO Ports Clock Enable */
    __HAL_RCC_GPIOC_CLK_ENABLE();



    /*Configure GPIO pin : PC13 */
    GPIO_InitStruct.Pin = GPIO_PIN_13;
    GPIO_InitStruct.Mode = GPIO_MODE_IT_FALLING;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    //GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
	HAL_NVIC_SetPriority(EXTI15_10_IRQn,10,0);
	HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);
}
int main(void) {
    // Initialize hardware (e.g., UART, peripherals, etc.)

    // Create a message buffer with a size of BUFFER_SIZE
    xMessageBuffer = xMessageBufferCreate(BUFFER_SIZE);
    button_init();
    if (xMessageBuffer == NULL) {
        // Handle error: Message buffer creation failed
        while (1); // Or appropriate error handling
    }

    // Create sender and receiver tasks
    xTaskCreate(vTaskSender, "Sender", configMINIMAL_STACK_SIZE, NULL, 1, &myTask1Handle);
    xTaskCreate(vTaskReceiver, "Receiver", configMINIMAL_STACK_SIZE, NULL, 1, &myTask2Handle);

    // Start the scheduler
    vTaskStartScheduler();

    // Should not reach here if the scheduler is running correctly
    while (1);
}

void vTaskSender(void *pvParameters) {
    const char *pcMessage = "Hello, FreeRTOS Message Buffer!";
    size_t xMessageLength = strlen(pcMessage) + 1; // +1 for null terminator

    for (;;) {
        // Send a message to the message buffer
        size_t xBytesSent = xMessageBufferSend(xMessageBuffer, (void *)pcMessage, xMessageLength, portMAX_DELAY);

        if (xBytesSent != xMessageLength) {
            // Handle error: Failed to send the complete message
        }

        // Simulate additional work
        vTaskDelay(pdMS_TO_TICKS(2000));
    }
}

void vTaskReceiver(void *pvParameters) {
    char pcBuffer[BUFFER_SIZE];
    size_t xReceivedLength;

    for (;;) {
        // Receive a message from the message buffer
        xReceivedLength = xMessageBufferReceive(xMessageBuffer, pcBuffer, sizeof(pcBuffer), portMAX_DELAY);

        if (xReceivedLength > 0) {
            // Process the received message
            pcBuffer[xReceivedLength] = '\0'; // Null-terminate the string
            // Example: Print or use the message
        } else {
            // Handle error: Failed to receive the message or timeout occurred
        }
        vTaskSuspend(NULL);
        // Simulate additional work
        vTaskDelay(pdMS_TO_TICKS(2000));
    }
}
void EXTI15_10_IRQHandler(void)
{
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_13);
}

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
    if (GPIO_Pin == GPIO_PIN_13)
    {
        BaseType_t xHigherPriorityTaskWoken = pdFALSE;
        xTaskResumeFromISR(myTask2Handle);
        portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
    }
}
