/*
 ******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2024-07-19

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include "stm32l4xx_hal.h"
#include "stm32l4xx.h"

#include <stdio.h>
/* FreeRTOS.org includes. */
#include "FreeRTOS.h"
#include "task.h"
#include "stream_buffer.h"
TaskHandle_t myTask1Handle = NULL;
TaskHandle_t myTask2Handle = NULL;

// Define buffer sizes
#define BUFFER_SIZE 100

// Define a handle for the stream buffer
StreamBufferHandle_t xStreamBuffer;

// Task function prototypes
void vTaskProducer(void *pvParameters);
void vTaskConsumer(void *pvParameters);
/* MX_GPIO_Init() should be generated by CubeMX or manually defined */
void button_init(void)
{
	GPIO_InitTypeDef GPIO_InitStruct;

	/* GPIO Ports Clock Enable */
	__HAL_RCC_GPIOC_CLK_ENABLE();
	/*Configure GPIO pin : PC13 */
	GPIO_InitStruct.Pin = GPIO_PIN_13;
	GPIO_InitStruct.Mode = GPIO_MODE_IT_FALLING;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	//GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
	HAL_NVIC_SetPriority(EXTI15_10_IRQn,10,0);
	HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);
}


int main(void) {
	// Initialize hardware (e.g., UART, peripherals, etc.)
	button_init();
	// Create a stream buffer with a buffer size of BUFFER_SIZE
	xStreamBuffer = xStreamBufferCreate(BUFFER_SIZE, 1);

	if (xStreamBuffer == NULL) {
		// Handle error: Stream buffer creation failed
		while (1); // Or appropriate error handling
	}

	// Create producer and consumer tasks
	xTaskCreate(vTaskProducer, "Producer", configMINIMAL_STACK_SIZE, NULL, 1, &myTask1Handle);
	xTaskCreate(vTaskConsumer, "Consumer", configMINIMAL_STACK_SIZE, NULL, 1, &myTask2Handle);

	// Start the scheduler
	vTaskStartScheduler();

	// Should not reach here if the scheduler is running correctly
	while (1);
}

void vTaskProducer(void *pvParameters) {
	char data[] = "Hello, FreeRTOS Stream Buffer!";
	size_t dataLength = sizeof(data);
	int errorvalue = 0;

	for (;;) {
		// Send data to the stream buffer
		size_t bytesWritten = xStreamBufferSend(xStreamBuffer, data, dataLength, portMAX_DELAY);

		if (bytesWritten != dataLength) {
			// Handle error: Failed to send all data
			errorvalue = 1;
		}

		// Simulate additional work
		vTaskDelay(pdMS_TO_TICKS(2000));
	}
}

void vTaskConsumer(void *pvParameters) {
	char buffer[BUFFER_SIZE];
	size_t bytesRead;
	int errorvalue = 0;

	for (;;) {
		// Receive data from the stream buffer
		bytesRead = xStreamBufferReceive(xStreamBuffer, buffer, sizeof(buffer), portMAX_DELAY);

		if (bytesRead > 0) {
			// Process the received data
			buffer[bytesRead] = '\0'; // Null-terminate the string
			// Example: Process or print the data
		} else {
			// Handle error: Failed to receive data or timeout occurred
			errorvalue = 1;
		}
		vTaskSuspend(NULL);

		// Simulate additional work
		vTaskDelay(pdMS_TO_TICKS(2000));
	}
}

void EXTI15_10_IRQHandler(void)
{
	HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_13);
}

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
	if (GPIO_Pin == GPIO_PIN_13)
	{
		BaseType_t xHigherPriorityTaskWoken = pdFALSE;
		xTaskResumeFromISR(myTask2Handle);
		portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
	}
}
